STEP_TO_TIME = 0.1
SIMULATION_TIME = 0.15 * 3600
STEPS = int(SIMULATION_TIME / STEP_TO_TIME)
MAX_CONTAINERS_AMMOUNT = 12


def settings_string():
    return f"t{SIMULATION_TIME}-st{STEP_TO_TIME}-m{MAX_CONTAINERS_AMMOUNT}"
