wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1654886311
    t:
      1:
      - 55
      4: 3.10.4
      5: 0.12.18
      8:
      - 3
      - 5
